version: 2
updates:
  - package-ecosystem: "pip"          # Specify pip as the package ecosystem
    directory: "/Bike-Helmet-Detection/ml_project"  # Directory containing requirements.txt
    schedule:
      interval: "monthly"              # Set the schedule to monthly
  - package-ecosystem: "github-actions" # Specify GitHub Actions for workflow dependencies
    directory: "/Bike-Helmet-Detection/.github/workflows"  # Directory containing workflow files
    schedule:
      interval: "monthly"              # Set to monthly for GitHub Actions updates
