version: 2
updates:
  - package-ecosystem: "pip"          # Specify pip as the package ecosystem
    directory: "/Bike-Helmet-Detection/ml_project"  # Directory containing requirements.txt
    schedule:
      interval: "manual"              # Set the schedule to manual
  - package-ecosystem: "github-actions" # Specify GitHub Actions for workflow dependencies
    directory: "/Bike-Helmet-Detection/.github/workflows"  # Directory containing workflow files
    schedule:
      interval: "manual"              # Set to manual for GitHub Actions updates
