# Generated by Django 5.0.1 on 2024-02-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_alter_image_image_alter_image_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='pred_image',
            field=models.ImageField(blank=True, null=True, upload_to='pred_images'),
        ),
        migrations.AddField(
            model_name='image',
            name='pred_video',
            field=models.FileField(blank=True, null=True, upload_to='pred_videos'),
        ),
    ]
