# Generated by Django 5.0.1 on 2024-02-03 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_image_pred_image_image_pred_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredImage',
            fields=[
                ('pred_image_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ml_app.image')),
                ('pred_image', models.ImageField(blank=True, null=True, upload_to='pred_images')),
                ('pred_video', models.FileField(blank=True, null=True, upload_to='pred_videos')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='pred_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pred_video',
        ),
    ]
