# Generated by Django 5.0.1 on 2024-02-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0006_predimage_remove_image_pred_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predimage',
            name='pred_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='predimage',
            name='pred_video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
